version: '3.9'

services:
  db:
      image: mysql:5.7.31
      container_name: 'database-node'
      restart: always
      environment: 
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=mvp-data-base
      ports: 
        - '3306:3306'
        
  app:
    links:
      - db
    depends_on:
      - db
    build: .
    container_name: node-api-app
    ports:
      - "3003:3003"
    
    
  