version: '3.5'

services:
  app:
    build: .
    image: mvp-node
    command: npm run dev 
    ports:
      - "3003:3003"
    volumes:
      - .:/usr/src/app

  db:
    container_name: 'database-node'
    image: mysql:5.7.31
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    restart: always
    ports: 
      - '3306:3306'
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mvp-data-base
  