CREATE TABLE MVP_DIRECTORY (
	id INT PRIMARY KEY AUTO_INCREMENT,
    directoryName VARCHAR(255) NOT NULL
);

CREATE TABLE MVP_UNITS(
	id INT PRIMARY KEY AUTO_INCREMENT,
    unitName VARCHAR(255) NOT NULL,
    latLong VARCHAR(255) NOT NULL,
    directoryId INT NOT NULL,
    FOREIGN KEY (directoryId) REFERENCES MVP_DIRECTORY(id)
);

CREATE TABLE MVP_USER (
	id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    unitId INT DEFAULT NULL,
    directoryId INT DEFAULT NULL,
    FOREIGN KEY (unitId) REFERENCES MVP_UNITS(id),
    FOREIGN KEY (directoryId) REFERENCES MVP_DIRECTORY(id)
);

CREATE TABLE MVP_SALES(
	id VARCHAR(255)PRIMARY KEY,
    sellerId VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP,
    amount FLOAT NOT NULL,
    roaming BOOLEAN DEFAULT FALSE,
    latLong VARCHAR(255) ,
    userUnitId INT ,
    directoryId INT,
    FOREIGN KEY (sellerId) REFERENCES MVP_USER(id),
    FOREIGN KEY (userUnitId) REFERENCES MVP_UNITS(id),
    FOREIGN KEY (directoryId) REFERENCES MVP_DIRECTORY(id)
);